version: '3.3'

services:
  visualizer:
    image: dockersamples/visualizer:stable
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - backend

  mysql:
    image: mysql:5.7
    restart: always
    networks:
      backend:
        aliases:
          - mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      
 
  wordpress:
    depends_on:
      - mysql
    links:
      - mysql:db
    image: wordpress
    restart: always
    volumes:
     - ./:/var/www/html
    networks:
      - frontend
      - backend
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_PASSWORD: wordpress
    deploy:
      mode: replicated
      replicas: 3
      
     
  nginx:
    depends_on:
      - wordpress
    links:
      - wordpress:web
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8083:80"
    networks:
      - frontend
    deploy:
      mode: replicated
      replicas: 1
      
volumes:
  db_data:

networks:
  frontend:
  backend: