version: '3.3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8083:80"
    networks:
      - frontend
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:latest
    volumes:
     - ./:/var/www/html
    networks:
      - frontend
      - backend
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: db_parola
    depends_on:
      - mysql
      
  mysql:
    image: mysql:5.7
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: db_root_parola
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: db_parola

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - backend
    depends_on:
      - mysql

volumes:
    db_data:
    wp-content:

networks:
  frontend:
  backend:
    driver: overlay