version: '3.3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8083:80"
    networks:
      - frontend
    depends_on:
      - wordpress1
      - wordpress2

  wordpress1:
    image: wordpress
    networks:
      - frontend
      - backend
    ports:
      - "80"
    environment:
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - mysql

  wordpress2:
    image: wordpress
    networks:
      - frontend
      - backend
    environment:
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - mysql
      
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: wordpress

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - backend
    depends_on:
      - mysql

networks:
  frontend:
  backend:
