version: '3.3'

services:
  visualizer:
    image: dockersamples/visualizer:stable
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - backend

  mysql:
    image: mariadb:10.1
    restart: always
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: wordpress
      MYSQL_PASSWORD_FILE: wordpress
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      
 
  wordpress:
    image: wordpress:4.7
    restart: always
    volumes:
     - ./:/var/www/html
    networks:
      - frontend
      - backend
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: wordpress
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      
     
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8083:80"
    networks:
      - frontend
    deploy:
      mode: replicated
      replicas: 1
      
volumes:
  db_data:

networks:
  frontend:
  backend: