version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - frontend
      - backend

  mysql:
    image: mysql:5.7
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
    networks:
      - backend
      
networks:
  frontend:
  backend: